### ISSUE TITLE
Fatal error: Call to a member function getPassword() on null in /assets/snippets/FormLister/plugin.userHelper.php on line 14

### ISSUE THREAD

**Issue by ricardo-lewis** [Pathologic/FormLister#102]
The above PHP error is triggered upon web user login.

Here's line 14:

https://github.com/Pathologic/FormLister/blob/4bdb544e7f2479818e9d85f6b7c322df32bbb5eb/assets/snippets/FormLister/plugin.userHelper.php#L14

I'm wondering why that variable `$userObj` is null.

I'm currently using WebLoginPE (in the absence of anything better) to handle web user authentication. 

Is WebLoginPE missing that variable?

Is there an "official" snippet that we should be using for logging web users in?

The only way I can get rid of that error is to disable the plugin from the Manager.

**Comment by Pathologic** [comment]
Disable userHelper plugin.
