### ISSUE TITLE
Перестал передоваться [*menutitle*] 

### ISSUE THREAD

**Issue by ultraviolet** [Pathologic/FormLister#103]
На версии Эво 1.4.4 успешно использовалась такая конструкция:
`<input type="hidden" name="heading" value="[*menutitle*]" />`
(это из шаблона formTpl)
`<tr valign="top"><td><b>Страница сайта:</b></td><td>[+heading+]</td></tr>`
(а это из reportTpl)

После обновления на Эво 1.4.5 menutitle не передается. В чём может быть дело/как можно исправить?

**Comment by Pathologic** [comment]
Обновить доклистер.

**Comment by ultraviolet** [comment]
Обновил, ничего не поменялось

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/ru/020_%D0%9F%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B.md#removeemptyplaceholders

**Comment by ultraviolet** [comment]
Попробовал сделать 0 (у меня было 1), то же самое. Пока `[*menutitle*]` вынесен в отдельный чанк, вызываемый в шаблоне Formlister `value="{{formHeading}}"`  (также работает в самом шаблоне вызов Docinfo на поле menutitle).
