### ISSUE TITLE
Where can I ask a question about FormLister? Specifically about error messages for File attachments

### ISSUE THREAD

**Issue by nick0** [Pathologic/FormLister#104]
Hello,

Where should I go to ask a question about FormLister? Here or somewhere else?

If here, I am stuck with error messages for a file attachment in a FormLister form and would greatly appreciate some help.

I have managed to get the file sending as an attachment with the report email using this line in the form html:
```
<input name="file[]" multiple type="file" value="[+file.value+]" /> 
```
I am stuck on the error messaging though - every time there is an error, 1000 is returned (which is the max file size for testing). 1000 also appears to be returned when a non allowed file type is uploaded.

The relevant file parameters in the FormLister call look like this
```
	&attachments=`file`
	&fileRules=`{
		"file": {
			"maxSize": "1000",
			"allowed": ".jpg,.jpeg,.pdf"
		}
	}`
	&rules=`{
		"file": {
			"maxSize": {
				"params": "1000",
				"message": "The maximum file size of attachments is 10MB"
			},
			"allowed": {
				"params": ".jpg,.jpeg,.pdf",
				"message": "That file type is not allowed for upload"
			}
		}
	}`
```

Can someone please help? 

I have looked at the docs but this is beyond me and I am stuck.

Thanks,.

**Comment by mnoskov** [comment]
You don't need `&rules` for file validation, only `&fileRules`.

And `&fileRules` section should be look like this:
```
{
	"file": {
		"maxSize": {
			"params": 1000,
			"message": "The maximum file size of attachments is 10MB"
		},
		"allowed": {
			"params": [
				["jpg", "jpeg", "pdf"]
			],
			"message": "That file type is not allowed for upload"
		}
	}
}
```

**Comment by nick0** [comment]
Thanks so much for the assist @mnoskov, I really appreciate it.
That is working. Thanks!
