### ISSUE TITLE
Не учитывает настройку "разница во времени" [(server_offset_time)]

### ISSUE THREAD

**Issue by webber12** [Pathologic/FormLister#106]
Параметр form.date https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/core/controller/Form.php#L381 при успешной отправке формы не учитывает настройку в админке "разница во времени" [(server_offset_time)] . Хоть и не критично, но все же.. ))

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/commit/5201b5357b88b4d956d05dccf8224356dfc8d742
