### ISSUE TITLE
How can I attach files

### ISSUE THREAD

**Issue by Sybrenb** [Pathologic/FormLister#109]
I'm trying to add a field to my form where people can attach files, but it just didn't seem to work for me. Everything works but the attached file just don't send.

I'm trying to send the file with this code:

Filerules:

&fileRules=`{
	"file": {
		"maxSize": {
			"params": 1000,
			"message": "The maximum file size of attachments is 10MB"
		},
		"allowed": {
			"params": [
				["jpg", "jpeg", "pdf"]
			],
			"message": "That file type is not allowed for upload"
		}
	}
}`

In report TPL:
[+filename+]

input field:
```
<div class="form-item form-100 [+file.errorClass+][+file.requiredClass+]">
						<label>Voeg eventueel enkele foto's toe</label>
						<input name="filename" multiple type="file" value="[+filename.value+]" /> 
					</div>
```

form enctype:
`<form enctype="multipart/form-data" action="[~[*id*]~]" method="post">`

Can someone please help me? Thanks

**Comment by Pathologic** [comment]
```
&attachments=`filename`
```
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/en/050_Mail_Sending.md#sending-files

**Comment by Sybrenb** [comment]
This worked for me thank you
