### ISSUE TITLE
Checkbox value

### ISSUE THREAD

**Issue by Sybrenb** [Pathologic/FormLister#114]
How can I get the checkbox value in Formlister?

Ive tried to do this:

HTML:
<label><input type="checkbox" name="aaa[]" id="aaa" class="aaa" value="aaa"></label>

Sender TPL:
[+aaa+]

But it just don't seem to work..

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/en/040_Data_Output.md
