### ISSUE TITLE
Reminder controler bug at line 167

### ISSUE THREAD

**Issue by ericfilippi** [Pathologic/FormLister#120]
Hello,

I think I found a bug on Reminder controler at line 167 :

`$uid = $this->getField($this->uidField);`
should be 
`$uid = $this->getField($this->getCFGDef('uidName', $this->uidField));`

Otherwise, if the &uidName parameter is set (and different from 'id'), the controler cannot retrieve the user data in the reset case of the process() function.

I tested with 2 scenarios to compare:

one with &uidName not set => the controler uses the value 'id' by default, everything goes ok

one with &uidName=`myid`
     => $uid = 'myid' in function renderReset() witch is ok because line 89 has the right code
     => $uid = '' in function process() on line 167
when I change line 167 to `$uid = $this->getField($this->getCFGDef('uidName', $this->uidField));`
     => $uid = 'myid' in function renderReset()
     => $uid = 'myid' in function process()
and everything does ok

Can you check and tell me if I'm right ?

Thank you for your help.
Eric.

**Comment by Pathologic** [comment]
Thanks.

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/commit/20ffcd4b601513d75fc130ba237c07f39a14446c
