### ISSUE TITLE
Параметры капчи в документации не совпадают

### ISSUE THREAD

**Issue by Dreamer0x01** [Pathologic/FormLister#51]
В документации, которая находится [здесь](http://docs.evolution-cms.com/Extras/Snippets/FormLister/%D0%9F%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B) 
не совпадают параметры капчи:
1) В документации дважды повторяется описание параметра captcha, причем, в обеих случаях - разное.
2) Параметры captchaWidth, captchaHeight - не работают. Вместо них работает задание параметров следующим образом (в документации не описан):

`&captchaParams='{
	"width":"300",
	"height":"100"
}'`

**Comment by Pathologic** [comment]
Да, документация устарела. Для капчи параметры теперь задаются в виде массива.
