### ISSUE TITLE
Installed with Extras - added default call - no e-mail

### ISSUE THREAD

**Issue by fourroses666** [Pathologic/FormLister#58]
I have installed FormLister on Evo 1.2.1 (Extras).
Then used the snippetcall from here: 
http://modx.im/blog/addons/4481.html

No email is being send.

Any idea why it doesn't work?

**Comment by Pathologic** [comment]
Probably, something is wrong with your mail configuration. Try &debug=`1`, maybe it will give you more informatioin. BTW, the last version is here in develop branch, not in Extras.

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/issues/53 - may be related.

**Comment by fourroses666** [comment]
Hi Pathologic.

There seems to be some caching issues.
I just tested it only works when unchecking cachable "Кэшируемый".
Then I do receive an email. 

I also have added a `&successTpl` now because I had no success message.

Then I get this;
[%form.submitLimit%] 1 [%form.minutes%].dfas
Is it because these fields are not translated?

Anyway, I will try the latest development version.

**Comment by Pathologic** [comment]
The snippet should be called uncached, as any other snippet working with $_REQUEST data, and there's no more caching issues.
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/core/lang/english/form.inc.php#L15 - if you don't set &successTpl you will get the default one from language file.
[%form.submitLimit%] 1 [%form.minutes%] - it's a message about submit limit, which is 1 submit in 60 seconds by default. Are you using non-English language in manager?

**Comment by fourroses666** [comment]
Yes, I'm using non English manager* _(Dutch/Nederlands)_

**Comment by Pathologic** [comment]
Yes, there's a problem, I'll fix it soon.

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/commit/02f69a84517e1a0a2fd1d37c27b31a78ba516b7f - I fixed in this update, give it a try.
