### ISSUE TITLE
Не работает input type="checkbox"  name="val[]"

### ISSUE THREAD

**Issue by dmi3yy** [Pathologic/FormLister#63]
То есть мы не можем сохранить корректно мультизначения одного поля. 

Просьба обьяснить как работать с такими полями формы. 
Для себя сделал вот так пока https://github.com/Pathologic/FormLister/pull/50/, но пул не приняли поэтому просьба описать как решать такую задачу :)

**Comment by Pathologic** [comment]
в скайпе мои ответы чего-то висят неотправленные. В общем, контроллер Content должен работать с произвольными моделями MODxAPI, а это заморочка конкретно modResource - там и нужно допиливать.

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/commit/3512ca72eef1d38ab2f9a44daf95f37403278838

**Comment by Sybrenb** [comment]
How can I get both values of the checkbox? It just reads the last one..
FormTPL:

```
<div class="form-item">
						<label>checkboxen*</label>
						<span><input class="checkbx" type="checkbox" name="checkbx" value="checkbx1" [+c.checkbx.checkbx1+]>checkbx </span>
						<span><input class="checkbx" type="checkbox" name="checkbx" value="checkbx2" [+c.checkbx.checkbx2+]>checkbx2</span>
						<div class="clear"></div>
					</div>
```

ReportTPL:
`<br>checkbx:[+checkbx+]`
