### ISSUE TITLE
не заполняется плейсхолдер form.messages

### ISSUE THREAD

**Issue by Dreamer0x01** [Pathologic/FormLister#65]
Не могу понять, то ли  я надуплил, то ли что-то после обновления на последнюю версию modx случилось - не выводится значение плейсхолдера [+form.messages+].
При этом по отдельности значения полей вида [+fieldname.error+] выводятся. 

При этом сама обертка <div class="form-messages"></div> в плейсхолдер помещается, но внутри нее мессаджей никаких нет. (хотя они при этом отобразились в форме в плейсхолдерах вида  [+fieldname.error+])

Шаблоны &messagesOuterTpl и иже с ними пробовал как задавать принудительно, так и оставлять значения по умолчанию - не результат не влияет.

**Comment by Pathologic** [comment]
В form.messages могут выводиться три типа сообщений: нарушения правила required,  нарушения остальных правил, произвольные сообщения, которые задаются методом addMessage. По умолчанию выводятся только последние.
Если нужно выводить остальные, то нужно изменить шаблоны:
```
&messagesTpl=`@CODE:<div class="form-group"><div class="col-sm-offset-2 col-sm-10">[+required+][+errors+][+messages+]</div></div>`
&messagesRequiredOuterTpl=`@CODE:<div class="panel panel-warning"><div class="panel-heading"><i class="glyphicon glyphicon-alert"></i> Вы не заполнили обязательные поля</div><div class="panel-body">[+messages+]</div></div>`
&messagesErrorOuterTpl=`@CODE:<div class="panel panel-danger"><div class="panel-heading"><i class="glyphicon glyphicon-alert"></i> Некоторые поля заполнены неверно</div><div class="panel-body">[+messages+]</div></div>`
&messagesOuterTpl=`@CODE:<div class="panel panel-default"><div class="panel-heading"></div><div class="panel-body">[+messages+]</div></div>`
```

**Comment by Pathologic** [comment]
Получилось?

**Comment by Dreamer0x01** [comment]
Да, офигенно! Спасибо. Только что наконец-то смог протестировать.

В документацию это бы как-то добавить - а то сам бы я вряд ли это нашел.
Спасибо!

**Comment by Dreamer0x01** [comment]
Есть все-таки еще проблема с этим. 
Сейчас перенес сайт на хостинг, и там по каким-то причинам отправка формы не работает.
При этом FormLister никаких сообщений не выдает, на странице после отправки просто остается все та же форма с заполненными сообщениями, ошибочных сообщений никаких не генерируется, хотя в логах ModX остается вот такая запись:

> ID события: | 0 | Код: | phpmailer
-- | -- | -- | --
Дата: | 21-07-2017 13:18:48 | Пользователь: |  
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/TroubleshootingMODxMailer Object (.......


Было бы здорово такие нештатные ситуации тоже в сообщения FormLister складывать, так как пока не залезешь в логи, причины не узнать.

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/commit/d9ee907b23feeccaea2f49c382abae2862e7121d - давно исправлено.

**Comment by Pathologic** [comment]
Блин, помню же что исправлял точно.

**Comment by Dreamer0x01** [comment]
Вот теперь все заработало. Спасибо!
