### ISSUE TITLE
Параметр &redirectTo не воспринимается, если передано число

### ISSUE THREAD

**Issue by Dreamer0x01** [Pathologic/FormLister#66]
Если указываю вот так - то редирект работает: 
> &redirectTo=`/zakaz_prinyat.html`

А если указываю не адрес, а номер ресурса, то вместо этого после отправки формы редирект происходит на адрес 0.html, то есть 404 стрницу:
> &redirectTo=`1951`

Вот так тоже пробовал - тоже не работает:

> &redirectTo=`[~1951~]`

(controller=Form)

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/commit/2b8ff3da4a1c9f4e3559acb53d16307270adcc44

**Comment by Dreamer0x01** [comment]
Благодарю! :)
