### ISSUE TITLE
Капча выводится "обрезанная"

### ISSUE THREAD

**Issue by Dreamer0x01** [Pathologic/FormLister#67]
Обратил внимание, что капча часто выводится как бы сильно увеличенная, и не вписывающаяся в заданные границы, из-за чего иногда возникают проблемы с ее читабельностью.
Вот скриншот и пример.
Было бы здорово, если бы можно было как-то менять и величину отступа от наружных границ картинки до крайних символов капчи. Причем. обратил внимание, что в стандартной капчи при выводе на странице авторизации в админке или при выводе eForm-ом такого эффекта нет.

Параметры вызова такие:
					captcha=`modxCaptcha`
					captchaParams=`{
						"width":"300",
						"height":"100"
					}`

![capcha](https://user-images.githubusercontent.com/12978365/28214471-06182314-68b3-11e7-8a7b-7ed43d72ebf4.png)

**Comment by Pathologic** [comment]
А как получается, что выводится 6 цифр?

**Comment by Pathologic** [comment]
Изменил алгоритм генерации, теперь символы меньше пляшут и больше вписываются в размеры (не идеально, но и такого как на картинке увидеть больше не получилось).

**Comment by Dreamer0x01** [comment]
> А как получается, что выводится 6 цифр?
В конфигурации ModX все слова для капчи заданы только цифрами.

Спасибо за фикс! Стало намного лучше.
