### ISSUE TITLE
Добавление пользователя в определённую группу

### ISSUE THREAD

**Issue by Ser1ous** [Pathologic/FormLister#76]
Пытался сделать регистрацию пользователя с добавлением в определённую группу.
После нескольких часов экспериментов, выяснил, что фактически идёт добавление нулевого пользователя в ту группу которую я задал в параметре.
Вот в этой строке
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/core/controller/Register.php#L132
После того как поместил эту же строку после проверки $result и подставил вместо 0 значение из $result, то у меня сразу всё отлично сработало. Возможно я что-то не понял в том как должен обрабатываться параметр "userGroups"

**Comment by Pathologic** [comment]
Так и должно быть, потому что в момент вызова метода пользователь еще не создан. https://github.com/AgelxNash/DocLister/blob/master/assets/lib/MODxAPI/modUsers.php#L263
