### ISSUE TITLE
FormLister и контролер Login

### ISSUE THREAD

**Issue by sergey-yabloncev** [Pathologic/FormLister#78]
Один момент заметил при работе с FormLister и контролером Login
Если ты авторизован в админке и авторизуешься как веб пользователь, тебя выбрасывает через определенный момент из админки и и разлогинивает как веб пользователя на сайте.
Это очень не удобно при авторизации через weblogin или webloginPE не наблюдалось 
Приходится при разработке открывать либо второй браузер либо открывать окно инкогнито

**Comment by Pathologic** [comment]
В админке где-то баг, но не понятно где.

**Comment by sergey-yabloncev** [comment]
Спасибо большое, закрываем
