### ISSUE TITLE
ответ в режим api

### ISSUE THREAD

**Issue by sergey-yabloncev** [Pathologic/FormLister#80]
есть страница куда форма стучится ajax
где вызывается несколько раз  снипет с разными formid
В ответ на отправку формы каждый вызов снипета отдает результат
хотя у формы задан formid, но почему то реагируют (обрабатывают запрос) и те вызовы снипета где отличается  formid

Получается что на одинз запрос одной формы отвечают все вызовы FormLister независимо от formid.
пример вызова
[!FormLister?
&formid=order
&api=1
&to=mailto
!]

**Comment by Pathologic** [comment]
Так и должно быть. Так что нужно делать вызов через сниппет типа такого:
```
if (isset($_POST['formid']) && isset($formid) && $_POST['formid'] == $formid) return $modx->runSnippet('FormLister', $params);
```

**Comment by sergey-yabloncev** [comment]
Так и сделал, но подумал это ошибка, спасибо большое.
