### ISSUE TITLE
Сломалась авторизация (контроллер Login) по username, если в username есть большие буквы

### ISSUE THREAD

**Issue by Dreamer0x01** [Pathologic/FormLister#82]
Собственно, сабж.
Вот с этим связано:
https://github.com/Pathologic/FormLister/commit/c9cf4e8f1622b2a06c078e38a6329e24735c9a39

При комментировании strtolower в 65 строчке все работает нормально.

**Comment by Pathologic** [comment]
Нужно в базе привести username в нижний регистр:
```
UPDATE `modx_web_users` SET `username`=LOWER(`username`)
```

**Comment by Dreamer0x01** [comment]
Но они-то там в верхних - именно в том написании, в котором юзеры регистрировались... Например, у многих никнеймы с большой буквы.

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/issues/281

**Comment by Dreamer0x01** [comment]
Прочитал. Так чего делать-то? У меня база пользователей из нескольких тысяч строк, перенес их с другого сайта. Просить всех пользователей поменять логины на маленькие буквы - как-то не правильно. У себя пока временно закоментил это преобразование, но ведь слетит при следующем обновлении..

**Comment by Pathologic** [comment]
Так зачем просить пользователей? Просто запросом поменять. А пользователь может вводить хоть uSeRnAmE при логине и будет залогинен.

**Comment by Dreamer0x01** [comment]
Там у многих пользователей логин еще и русскоязычный. Например, "Екатерина Иванова". Их в нижний регистр переводить нельзя :( я, конечно, предложу заказчику переделать авторизацию с авторизации по никнейму на авторизацию по емейлу, но могут и не согласиться на такие перемены.

**Comment by Pathologic** [comment]
Тогда остается расширить контроллер и использовать имя без strtolower

**Comment by Pathologic** [comment]
А чем не подошло поле fullname?

**Comment by Dreamer0x01** [comment]
Уже используется под полные ФИО. 
Там на сайте некоторые пользователи нормально зарегились - к примеру, логин = 'irina_ivanovna' и fullname = 'Ирина Ивановна Иванова', а у других при таком  fullname = 'Ирина Ивановна Иванова'  логин выставлен в 'Ирина Ивановна' :)
