### ISSUE TITLE
&rules

### ISSUE THREAD

**Issue by nuclear4547** [Pathologic/FormLister#84]
Если в rules указать такое правило для поля: `"email":{ "email":"Проверьте корректность Вашего адреса" }` Без указания обязательности заполнения `"required":"Заполните это поле"` не проходит валидацию и все равно требует заполнить поле, это вроде как не правильно. пустое поле тоже должно проходить данную проверку

**Comment by Pathologic** [comment]
"!email":{ "email":"Проверьте корректность Вашего адреса"}
