### ISSUE TITLE
replyTo parameter not working

### ISSUE THREAD

**Issue by pmfx** [Pathologic/FormLister#85]
In my call I have:
```
&replyTo=`[+email.value+]`
```
This is the error I get in system log after submitting form:
```
Invalid address: (Reply-To): [+email.value+]
```
Delivered email message doesn't have "reply to" set.

EVO 1.4.0

**Comment by Pathologic** [comment]
Placeholders are not parsed in mailer parameters, I'll add this feature later. But you can set any parameters using prepare snippet:
```
$FormLister->config->setConfig(array('replyTo'=>$FormLister->getField('email')));
```

**Comment by pmfx** [comment]
Thanks! This is working fine now, perfect.
BTW I found this (the same issue) example in latest EVO Sample Site in "evoAjax" plugin:

![screenshot_1](https://user-images.githubusercontent.com/10888055/35724911-b165c80c-07ff-11e8-880a-7002e8158ddf.png)

Causing same error in log.

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/blob/master/assets/snippets/FormLister/docs/en/050_Mail_Sending.md#parsemailerparams - since 1.7.14
