### ISSUE TITLE
parseMailerParams и replyTo

### ISSUE THREAD

**Issue by denisenkor** [Pathologic/FormLister#86]
Если включить parseMailerParams=`1` а в replyTo=`@CODE:[+email+]` то собственно ничего не работает, поле подставляется пустым в письмо, т.к. парсер не убирает '@CODE:' и phpmailr на это ругается, если не указывать @CODE то парсер просто не подставляет значение поля email. 

Это баг или я что-то не правильно делаю?

**Comment by Pathologic** [comment]
@CODE не нужно, а плейсхолдер может вырезаться из-за phx
