### ISSUE TITLE
Не работает залогинивание русскоязычных имен, содержащих прописные буквы.

### ISSUE THREAD

**Issue by Dreamer0x01** [Pathologic/FormLister#88]
К примеру, пользователь зарегистрировался с логином Аида. В базе сохранилось аида. 
Пользователь логинится, набирая Аида именно с большой буквы - и логин не проходит. 
Если залогинится с маленькой, то проходит.
Снова причина обнаружилась в этом месте:
https://github.com/Pathologic/FormLister/blob/42528f57f6ac68015c89e066ae8d756fea680e4c/assets/snippets/FormLister/core/controller/Login.php#L67

После правки вот этой строки (№67 в файле FormLister/core/controller/Login.php) на 
$login = 	mb_strtolower($login,'utf-8');
заработало.

Возможно, где-то ранее надо какие-то настройки проверить/применить, тогда и с обычным strtolower заработает, без привязывания конкретно к utf-8, но я не понял, где именно. В настройки хостинга залезть не удается, чтобы там всякие локали и прочие параметры задать.

**Comment by Pathologic** [comment]
В приципе я могу поменять на mb_, но лучше следить за такими вещами и ограничивать пользователей правилами валидации.

**Comment by Dreamer0x01** [comment]
Так а с точки зрения валидации сейчас все корректно. 
Есть, к примеру, пользователь с логином "Аида", в базе данных сохранено как "аида". При авторизации пользователь вводит логин с большой буквы. Что вполне допустимо. 
Зарегистрирован пользователь в системе еще с тех времен, когда сайт вообще не на модексе был...
Запретить русскоязычные логины - получим шквал претензий. Ну а учитывая, что они любят свои имена или фамилии вводить в качестве логина, то нужно разрешить им это писать с большой буквы.

**Comment by Dreamer0x01** [comment]
Да, надо, похоже, не только в этом файле на mb_strtolower исправить, но и в Register, да и в Profile тоже. Дело  в том, что если тестировать сайт на Windows, то под ней установить локаль под utf-8 вообще не удается, и в этом случае функции strtolower не только не меняют содержимое, но и портят его. Причем, не помогает даже предварителное преобразование русскоязычных логинов в prepare, так как в контроллере перед $this->user->create($fields) стоит $fields['username'] = strtolower($fields['username']), и вот на этом этапе username превращается в кракозябры.

**Comment by 0test** [comment]
А я сижу и думаю, почему юзеры меня матерят и не могут своё имя с большой буквы написать...
