### ISSUE TITLE
"&to" parameter

### ISSUE THREAD

**Issue by modxuser** [Pathologic/FormLister#90]
I am experiencing problems when using the "&to" with this format "test.test@" e.g

This works:
```
&to=`test@test.com`
```
This doesn't
```
&to=`test.test@test.com`
```
I tried adding the email to the emailsender parameter in the config and then call it like this
```
&to=`[(emailsender)]`
```
But it still doesn't work with the format "test.test" (it works with test@)

**Comment by Pathologic** [comment]
I've checked and it works:
![image](https://user-images.githubusercontent.com/3012304/36699005-7e9aa5c6-1b5c-11e8-95a2-298484e589fe.png)

**Comment by modxuser** [comment]
I should have chosen my wording a little better

The form is processed, but I don't get a report - I have checked the spam folder, but nothing in it

I have now tested with 8 different addresses

5 x test@ - **all work**
3 x test.test@ - **none work**

**Comment by Pathologic** [comment]
There's nothing to do with FormLister or even MODX here, it's something wrong with your hosting or smtp provider. Try debugmail.io for tests.

**Comment by modxuser** [comment]
So why do the eForm forms work ?

**Comment by modxuser** [comment]
I will go through the form again in the morning, to ensure I haven't done anything wrong, which if I had, nothing would work.

But anyway, here the result with eForm:

![eform-result](https://user-images.githubusercontent.com/1859868/36700868-6e095596-1b51-11e8-9a83-ee5ed24146a9.jpg)

Note: this is using a live server - the tests are being run on the same install

**Comment by modxuser** [comment]
Re-checked the code but still doesn't work, eForm sends without a problem, so giving up on this

**Comment by Pathologic** [comment]
I've cheked in real environment and it works as well.
![image](https://user-images.githubusercontent.com/3012304/36849162-55873ce8-1d74-11e8-8636-e68b60c6d41b.png)

**Comment by modxuser** [comment]
As mentioned, i've sacked it - it works with single names and as it was only for testing I no-longer care :)

But it is strange that eForm works without a problem on my server

**Comment by Pathologic** [comment]
I don't understand, what are the single names?
